---
 engines:
   duplication:
     enabled: true
     config:
       languages:
       - javascript
   eslint:
     enabled: true
   fixme:
     enabled: true
 exclude_paths:
 - docs/
 - lib/
 - test/
